// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUaVL_FjdJ1wN7-zJEGkEcKszGCsV6VUM',
    appId: '1:1094359764954:web:04fc2838243a2d6f0c7ae3',
    messagingSenderId: '1094359764954',
    projectId: 'attendi-3b910',
    authDomain: 'attendi-3b910.firebaseapp.com',
    storageBucket: 'attendi-3b910.appspot.com',
    measurementId: 'G-058L0KEF18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkcZTHh6OsIvNHI0tEh8KlHSTdd9zS7OQ',
    appId: '1:1094359764954:android:0fd9f09fa45a1f4e0c7ae3',
    messagingSenderId: '1094359764954',
    projectId: 'attendi-3b910',
    storageBucket: 'attendi-3b910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkRX6wj3C4WmpQUtaLwYzvdbg4e1iJiKQ',
    appId: '1:1094359764954:ios:6d9424823230589f0c7ae3',
    messagingSenderId: '1094359764954',
    projectId: 'attendi-3b910',
    storageBucket: 'attendi-3b910.appspot.com',
    iosClientId: '1094359764954-mc2too97lf8kc03p71duumbfu6cikf3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkRX6wj3C4WmpQUtaLwYzvdbg4e1iJiKQ',
    appId: '1:1094359764954:ios:6d9424823230589f0c7ae3',
    messagingSenderId: '1094359764954',
    projectId: 'attendi-3b910',
    storageBucket: 'attendi-3b910.appspot.com',
    iosClientId: '1094359764954-mc2too97lf8kc03p71duumbfu6cikf3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendiApp',
  );
}
