// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnaGoO7LvHjmxlQOY26mH36tTk4VLrAfM',
    appId: '1:869681890039:web:67162c64d33c581c0049f2',
    messagingSenderId: '869681890039',
    projectId: 'students-333d0',
    authDomain: 'students-333d0.firebaseapp.com',
    storageBucket: 'students-333d0.appspot.com',
    measurementId: 'G-9BKQW9YJ80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt0Jnjg9VVfi9W_JrJnoTQB9mYFgowWC0',
    appId: '1:869681890039:android:a424e1759cac9d170049f2',
    messagingSenderId: '869681890039',
    projectId: 'students-333d0',
    storageBucket: 'students-333d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcMVTOZ9gBmr9UM7BEZfxG9-VpmwcXq6A',
    appId: '1:869681890039:ios:618b11f0f317729e0049f2',
    messagingSenderId: '869681890039',
    projectId: 'students-333d0',
    storageBucket: 'students-333d0.appspot.com',
    iosClientId: '869681890039-33b2t2emqvqj6is6teibemoetjg8ncc9.apps.googleusercontent.com',
    iosBundleId: 'jin.mychew.shopingmallFlutter',
  );
}
